file_format: "1"
id: dm_4x6_3
Name: dm_4x6_3
type: shield
url: https://github.com/francislz/zmk-config
requires:
  - nrfmicro_11
features:
  - keys
  - display
  - encoders
siblings:
  - dm_4x6_3_left
  - dm_4x6_3_right